apiVersion: v1
kind: ResourceQuota
metadata:
  name: sandbox-quota
  namespace: containment-sandbox
  labels:
    app.kubernetes.io/part-of: containment
    app.kubernetes.io/component: sandbox-limits
spec:
  hard:
    pods: "30"
    requests.cpu: "8"
    requests.memory: "16Gi"
    limits.cpu: "16"
    limits.memory: "32Gi"
    requests.ephemeral-storage: "30Gi"
    limits.ephemeral-storage: "60Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: sandbox-limits
  namespace: containment-sandbox
  labels:
    app.kubernetes.io/part-of: containment
    app.kubernetes.io/component: sandbox-limits
spec:
  limits:
    - default:
        cpu: "1000m"
        memory: "1024Mi"
        ephemeral-storage: "2Gi"
      defaultRequest:
        cpu: "250m"
        memory: "256Mi"
        ephemeral-storage: "512Mi"
      max:
        cpu: "2000m"
        memory: "4096Mi"
        ephemeral-storage: "8Gi"
      min:
        cpu: "100m"
        memory: "128Mi"
      type: Container
