/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgentRunRouteImport } from './routes/_authenticated/agent-run'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPolicyRouteImport } from './routes/_authenticated/policy'
import { Route as ApiPublicV1GuardRouteImport } from './routes/api/public/v1/guard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentRunRoute = AuthenticatedAgentRunRouteImport.update({
  id: '/agent-run',
  path: '/agent-run',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPolicyRoute = AuthenticatedPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicV1GuardRoute = ApiPublicV1GuardRouteImport.update({
  id: '/api/public/v1/guard',
  path: '/api/public/v1/guard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agent-run': typeof AuthenticatedAgentRunRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/policy': typeof AuthenticatedPolicyRoute
  '/api/public/v1/guard': typeof ApiPublicV1GuardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agent-run': typeof AuthenticatedAgentRunRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/policy': typeof AuthenticatedPolicyRoute
  '/api/public/v1/guard': typeof ApiPublicV1GuardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agent-run': typeof AuthenticatedAgentRunRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/policy': typeof AuthenticatedPolicyRoute
  '/api/public/v1/guard': typeof ApiPublicV1GuardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agent-run'
    | '/console'
    | '/dashboard'
    | '/policy'
    | '/api/public/v1/guard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agent-run'
    | '/console'
    | '/dashboard'
    | '/policy'
    | '/api/public/v1/guard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agent-run'
    | '/_authenticated/console'
    | '/_authenticated/dashboard'
    | '/_authenticated/policy'
    | '/api/public/v1/guard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicV1GuardRoute: typeof ApiPublicV1GuardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agent-run': {
      id: '/_authenticated/agent-run'
      path: '/agent-run'
      fullPath: '/agent-run'
      preLoaderRoute: typeof AuthenticatedAgentRunRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policy': {
      id: '/_authenticated/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof AuthenticatedPolicyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/v1/guard': {
      id: '/api/public/v1/guard'
      path: '/api/public/v1/guard'
      fullPath: '/api/public/v1/guard'
      preLoaderRoute: typeof ApiPublicV1GuardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentRunRoute: typeof AuthenticatedAgentRunRoute
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPolicyRoute: typeof AuthenticatedPolicyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentRunRoute: AuthenticatedAgentRunRoute,
  AuthenticatedConsoleRoute: AuthenticatedConsoleRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPolicyRoute: AuthenticatedPolicyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicV1GuardRoute: ApiPublicV1GuardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
