/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicV1GuardRouteImport } from './routes/api/public/v1/guard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1GuardRoute = ApiPublicV1GuardRouteImport.update({
  id: '/api/public/v1/guard',
  path: '/api/public/v1/guard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/v1/guard': typeof ApiPublicV1GuardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/v1/guard': typeof ApiPublicV1GuardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/v1/guard': typeof ApiPublicV1GuardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/v1/guard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/v1/guard'
  id: '__root__' | '/' | '/api/public/v1/guard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicV1GuardRoute: typeof ApiPublicV1GuardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/guard': {
      id: '/api/public/v1/guard'
      path: '/api/public/v1/guard'
      fullPath: '/api/public/v1/guard'
      preLoaderRoute: typeof ApiPublicV1GuardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicV1GuardRoute: ApiPublicV1GuardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
